api/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'api_v1'

router = routers.DefaultRouter()

router.register(r'todos', views.TodoListViewSet, basename='todos')
router.register(r'criterion', views.CriteryView, basename='criterion')
router.register(r'solutions', views.SolutionView, basename='solutions')
router.register(r'problems', views.ProblemViewSet, basename='problems')
router.register(r'categories', views.CategoryViewSet, basename='categories')
router.register(r'problemList', views.ProblemViewList, basename='problemList')
router.register(r'observer/scale/(?P<scale_id>\d+)', views.MetricViewSet, basename='metrics')
router.register(r'observer/data', views.ObserverDataView, basename='observer_data')
router.register(r'observer', views.ObserverViewSet, basename='observer')
router.register(r'scales', views.ScalesViewSet, basename='scales')
router.register(r'scales/nik/(?P<nik>@\w+)', views.ScalesViewSet, basename='scales_nik')
router.register(r'users', views.UserViewList, basename='users')
router.register(r'posts', views.PostViewSet, basename='posts')

urlpatterns = [
    path('v1/', include(router.urls)),
]

problem_solving/urls.py
from django.urls import path
from . import views


app_name = 'problem_solving'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about, name='about_us'),
    path('todo/', views.todo, name='todo'),
    path('registration/', views.SignUp.as_view(), name='registration'),
    path('byaes/', views.byaes, name='byaes'),
    path('technical_maintenance/', views.technical_maintenance, name='technical_maintenance'),
    path('observation/', views.observation, name='observation'),
    path('notifications/', views.notification, name='notifications'),
    path('chat/', views.chat, name='chat'),

]

problem_solving_framework/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # templates pages
    path('', include("problem_solving.urls", namespace="problem_solving")),
    # api
    path('api/', include("api.urls", namespace="api_v1")),
    # chat_api
    path('api/', include('chat.urls', namespace='api_v1')),
    # auth
    # path(r"^account/", include(("account.urls", "auth"), namespace="auth")),
    path('accounts/', include(("django.contrib.auth.urls", "auth"), namespace="auth")),
]

templates/includes/footer.html
{% load custom_filters %}
{% with view_name=request.resolver_match.view_name %}
<div class="container">
  <footer class="mt-5">
    <ul class="nav justify-content-center border-bottom">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'problem_solving:about_us' %}">О сайте</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="mailto:problem.solving.framevork@gmail.com">Email</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://t.me/Unikalnynik>Telegram">Telegram</a>
      </li>
    </ul>
    <p class="text-center text-muted">Beta testing version 0.3.0</p>
    <p class="text-center text-muted p-0">Copyright {% now "Y" %}</p>
  </footer>
</div>
{% endwith %}

templates/includes/navbar.html
{% load custom_filters %}
{% with view_name=request.resolver_match.view_name %}
  <nav class="navbar navbar-expand-lg bg-body-tertiary shadow">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'problem_solving:index' %}">Problem solving framework</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
              data-bs-target="#offcanvasNavbar"
              aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
           aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Problem solving framework</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas"
                  aria-label="Закрыть"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">

            <li class="nav-item">
              <a class="nav-link {{ 'problem_solving:about_us'|activate_if_matched:view_name }}"
                 aria-current="page" href="{% url 'problem_solving:about_us' %}">О сайте</a>
            </li>
            {% if user.is_authenticated %}
              {#              <li class="nav-item">#}
              {#                <a class="nav-link {{ 'auth:password_change'|activate_if_matched:view_name }}"#}
              {#                   aria-current="page"#}
              {#                   href="{% url 'auth:password_change' %}">Изменить пароль</a>#}
              {#              </li>#}
              <li class="nav-item">
                <a class="nav-link {{ 'problem_solving:index'|activate_if_matched:view_name }}"
                   aria-current="page" href="{% url 'problem_solving:index' %}">Главная</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ 'problem_solving:observation'|activate_if_matched:view_name }}"
                   aria-current="page" href="{% url 'problem_solving:observation' %}">Наблюдения</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ 'problem_solving:byaes'|activate_if_matched:view_name }}"
                   aria-current="page" href="{% url 'problem_solving:byaes' %}">Вероятности</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ 'problem_solving:todo'|activate_if_matched:view_name }}"
                   aria-current="page" href="{% url 'problem_solving:todo' %}">Список задач</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ 'problem_solving:chat'|activate_if_matched:view_name }}"
                   aria-current="page" href="{% url 'problem_solving:chat' %}">Чат</a>
              </li>
              <li class="nav-item ms-lg-3 ps-2 ps-lg-0 border-start">
                <a class="nav-link" aria-current="page"
                   href="{% url 'auth:logout' %}">Выйти</a>
              </li>
            {% else %}
              <li class="nav-item ms-lg-3 ps-2 ps-lg-0  border-start">
                <a class="nav-link {{ 'auth:login'|activate_if_matched:view_name }}"
                   aria-current="page"
                   href="{% url 'auth:login' %}">Войти</a>
              </li>
              <li class="nav-item ps-2 ps-lg-0">
                <a class="nav-link {{ 'problem_solving:registration'|activate_if_matched:view_name }}"
                   aria-current="page"
                   href="{% url 'problem_solving:registration' %}">Регистрация</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>
{% endwith %}