api/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'api_v1'

router = routers.DefaultRouter()

router.register(r'todos', views.TodoListViewSet, basename='todos')
router.register(r'criterion', views.CriteryView, basename='criterion')
router.register(r'solutions', views.SolutionView, basename='solutions')
router.register(r'problems', views.ProblemViewSet, basename='problems')
router.register(r'categories', views.CategoryViewSet, basename='categories')
router.register(r'problemList', views.ProblemViewList, basename='problemList')
router.register(r'observer/scale/(?P<scale_id>\d+)', views.MetricViewSet, basename='metrics')
router.register(r'observer/data', views.ObserverDataView, basename='observer_data')
router.register(r'observer', views.ObserverViewSet, basename='observer')
router.register(r'scales', views.ScalesViewSet, basename='scales')
router.register(r'scales/nik/(?P<nik>@\w+)', views.ScalesViewSet, basename='scales_nik')
router.register(r'users', views.UserViewList, basename='users')
router.register(r'posts', views.PostViewSet, basename='posts')

urlpatterns = [
    path('v1/', include(router.urls)),
]

problem_solving/urls.py
from django.urls import path
from . import views


app_name = 'problem_solving'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about, name='about_us'),
    path('todo/', views.todo, name='todo'),
    path('registration/', views.SignUp.as_view(), name='registration'),
    path('byaes/', views.byaes, name='byaes'),
    path('technical_maintenance/', views.technical_maintenance, name='technical_maintenance'),
    path('observation/', views.observation, name='observation'),
    path('notifications/', views.notification, name='notifications'),
    path('chat/', views.chat, name='chat'),

]

problem_solving_framework/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # templates pages
    path('', include("problem_solving.urls", namespace="problem_solving")),
    # api
    path('api/', include("api.urls", namespace="api_v1")),
    # chat_api
    path('api/', include('chat.urls', namespace='api_v1')),
    # auth
    # path(r"^account/", include(("account.urls", "auth"), namespace="auth")),
    path('accounts/', include(("django.contrib.auth.urls", "auth"), namespace="auth")),
]

templates/todo/main-todo.html
{% extends 'base.html' %}
{% block title %}Задачи{% endblock %}
{% block content %}
  {% include 'todo/todo.html' %}
{% endblock %}

templates/todo/newTask.html
<div class="pb-2 collapse" id="collapseNewTask">
  <div class="card">
    <div class="card-body">
      <div class="d-flex flex-column gap-3 align-items-center">
        <input type="text" class="form-control form-control-lg"
               id="title"
               :placeholder="$store.todo.error ? 'title is required' : 'title' "
               x-model="newTask.title"
        >
        <textarea type="text" class="form-control form-control-lg"
                  id="content"
                  placeholder="content"
                  rows="3"
                  x-model="newTask.content"

        ></textarea>
        <input type="date" class="form-control form-control-lg"
               x-model="newTask.due_date"
               id="date">
        <div class="d-flex w-100 gap-2 align-self-end">
{#          <select class="CATEGORY form-control form-control-lg "#}
{#                  x-model="newTask.category">#}
{#            <option selected>Category</option>#}
{##}
{#            <template x-for="{key, value} in $store.todo.categories" :key="value">#}
{#              <option x-text="key"#}
{#                      :value="value"#}
{#                      :selected="value === $store.newTask?.category"#}
{#              ></option>#}
{#            </template>#}
{#          </select>#}
{#          <select class="PROBLEM form-control form-control-lg"#}
{#                  x-model="newTask">#}
{#            <option selected="true">Problem</option>#}
{##}
{#            <template x-for="{title, id} in $store.todo.problems" :key="id">#}
{#              <option x-text="title"#}
{#                      :value="id"#}
{#              ></option>#}
{#            </template>#}
{#          </select>#}
        </div>
        <div>
          <button type="button"
                  class="btn btn-primary"
                  x-text="'save'"
                  @click="$store.todo.taskUpdate(newTask)"
          >
          </button>
          <button type="button"
                  class="btn btn-primary"
                  x-text="'Reset'"
                  @click="$store.todo.resetForm(newTask)"
          >
          </button>
        </div>
      </div>
    </div>
  </div>
  <hr class="my-4">
</div>

templates/todo/table.html
{% load static %}
<div class="table-responsive">
  <table
      class="table mb-0 table-hover"
      :class="location.pathname === '/' && 'table-sm'"
      id="todoTable">
    <thead>
    <tr>
      <template x-for="col in Object.keys($store.todoInputValue)">
        <th scope="col"
            x-show="col !== 'id' && col !== 'category' && $store.todo.cols[col]"
            :class="col === 'created' || col === 'due_date' ? 'cursor-pointer' : '' "
            x-html="col"
            @click="col === 'created' || col === 'due_date' ?
            $store.todo.filterTodos('ordering', col) : '' "
        ></th>
      </template>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <template
        x-for="{title, content, problem, category, completed, created, due_date, id} in $store.todo.todos"
        :key="id">
      <tr class="fw-normal">
        <td class="align-middle" x-show="false">
          <h6 class="mb-0"><span x-text="id"></span></h6>
        </td>
        <td class="align-middle" x-show="$store.todo.cols['title']">
          <h6 class="mb-0"><span class="text-truncate" x-text="title"></span></h6>
        </td>
        <td class="align-middle" x-show="$store.todo.cols['content']">
          <h6 class="mb-0"><span class="text-truncate" x-text="content"></span></h6>
        </td>
        <td class="align-middle" x-show="$store.todo.cols['created']">
          <h6 class="mb-0"><span x-text="created"></span></h6>
        </td>
        <td class="align-middle" x-show="$store.todo.cols['due_date']">
          <h6 class="mb-0"><span x-text="due_date"></span></h6>
        </td>
        <td class="align-middle" x-show="false">
          <h6 class="mb-0"><span x-text="category && category.name"></span></h6>
        </td>
        <td class="align-middle" x-show="$store.todo.cols['problem']">
          <h6 class="mb-0"><span x-text="problem && problem.title"></span></h6>
        </td>
        <td class="flex-row w-25">
          <img @click="$store.todo.toggleTodo(id)"
               class="cursor-pointer"
               :src="completed ? $store.todo.done : $store.todo.make"
               width="20"
               alt="done"/>
          <img @click="$store.todo.deleteTodo(id)"
               class="cursor-pointer"
               src="{% static 'icons/todo/delete.png' %}"
               alt="delete"
               width="20"/>
          <img @click="$store.todo.openChangeForm(id, newTask, $refs.openFormTask)"
               class="cursor-pointer"
               src="{% static 'icons/todo/exchange.png' %}"
               alt="change"
               width="20"/>
        </td>
      </tr>
    </template>
    </tbody>
  </table>
</div>

templates/todo/todo.html
{% load static %}
<section>
  {#TODO обработка случая с пустым списокм #}
  <div class="container px-0 py-5" x-data="{newTask: {
    author: USER.id,
    title: '',
    content: '',
    created: TODAY,
    due_date: DEFAULT_DUE_DATE,
    category: 0,
    problem: null,
    completed: false
  }}">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col">
        <div class="card" id="list1" >
          <div class="card-header d-flex justify-content-between align-items-center">
            <a class="nav-link" href="{% url 'problem_solving:todo' %}">
              <h6 class="card-title">TO DO</h6>
            </a>
            <a class="link"
               x-ref="openFormTask"
               data-bs-toggle="collapse"
               data-bs-target="#collapseNewTask"
               aria-expanded="false"
               aria-controls="collapseNewTask">
              Add a new task
            </a>
          </div>
          <div x-data class="card-body">
{#             Новая задача#}
            {% include 'todo/newTask.html' %}
{#             Управление таблицей#}
            <div class="d-flex flex-wrap align-items-center mb-2">
{#               Скрыть/показать колонки#}
              {% include 'todo/toggleColumn.html' %}
{#               Сортировка#}
              <div class="dropdown PROBLEMS">
                <button class="btn dropdown-toggle"
                        type="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">
                  Problems
                </button>
                <ul class="dropdown-menu">
                  <li class="form-check form-switch m-1">
                    <label class="form-check-label"
                           for="resetProblem"> reset
                    </label>
                    <input class="form-check-input"
                           @click="$store.todo.filterTodos('problem',  '')"
                           type="radio"
                           name="filterProblems"
                           id="resetProblem"
                    >
                  </li>
                  <template
                      x-for="{title, id} in $store.todo.problems"
                      :key="id">
                    <li class="form-check form-switch m-1">
                      <label class="form-check-label"
                             x-text="title"
                             :for="'check' + title">
                      </label>
                      <input class="form-check-input"
                             @click="$store.todo.filterTodos('problem',  id)"
                             type="radio"
                             name="filterProblems"
                             :id="'check' + title"
                             :value="id"
                             :checked="$store.todo.filterBody.problem == id"
                      >
                    </li>
                  </template>
                </ul>
              </div>
{#              <div class="dropdown CATEGORIES">#}
{#                <button class="btn dropdown-toggle"#}
{#                        type="button"#}
{#                        data-bs-toggle="dropdown"#}
{#                        aria-expanded="false">#}
{#                  Categories#}
{#                </button>#}
{#                <ul class="dropdown-menu">#}
{#                  <li class="form-check form-switch m-1">#}
{#                    <label class="form-check-label"#}
{#                           for="resetCategiry"> reset#}
{#                    </label>#}
{#                    <input class="form-check-input"#}
{#                           @click="$store.todo.filterTodos('category', '')"#}
{#                           type="radio"#}
{#                           name="filterCategory"#}
{#                           id="resetCategory"#}
{#                    >#}
{#                  </li>#}
{#                  <template#}
{#                      x-for="{key, value} in $store.todo.categories" :key="value">#}
{#                    <li class="form-check form-switch m-1">#}
{#                      <label class="form-check-label"#}
{#                             x-text="key"#}
{#                             :for="'check' + key">#}
{#                      </label>#}
{#                      <input class="form-check-input"#}
{#                             @click="$store.todo.filterTodos('category',  value)"#}
{#                             type="radio"#}
{#                             name="filterCategory"#}
{#                             :id="'check' + key"#}
{#                             :value="value"#}
{#                             :checked="$store.todo.filterBody.category == value"#}
{#                      >#}
{#                    </li>#}
{#                  </template>#}
{#                </ul>#}
{#              </div>#}
              <div class="form-check">
                <label class="form-check-label"
                       :class="$store.todo.filterBody.completed === '' && 'cursor-pointer text-decoration-underline'"
                       for="resetCategiry"
                       @click="$store.todo.filterTodos('completed', '')"
                > Completed
                </label>
                <input class="form-check-input"
                       x-model="$store.todo.filterBody.completed"
                       @click="$store.todo.filterTodos('completed', !$store.todo.filterBody.completed)"
                       type="checkbox"
                       name="filterCompleted"
                       id="resetCategory"
                       :value="$store.todo.filterBody.completed"
                >
              </div>
            </div>
{#             Задачи#}
            {% include 'todo/table.html' %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script src="{% static 'js/todo/todo.js' %}"></script>

templates/todo/toggleColumn.html
<div class="dropdown COLUMNS">
  <button class="btn dropdown-toggle"
          type="button"
          data-bs-toggle="dropdown"
          aria-expanded="false">
    Columns
  </button>
  <ul class="dropdown-menu">
    <template x-for="col in Object.keys($store.todoInputValue)">
      <li class="form-check form-switch m-1"
          x-show="col !== 'id' && col !== 'category'">
        <label class="form-check-label"
               x-text="col"
               :for="'check' + col">
        </label>
        <input class="form-check-input"
               @click="$store.todo.toggleColumn(col)"
               type="checkbox"
               :id="'check' + col"
               :checked="$store.todo.cols[col]">
      </li>
    </template>
  </ul>
</div>